// ============================================
// DATA.JS — Dữ liệu từ vựng tiếng Anh cho bé
// 15 chủ đề, mỗi chủ đề ~10 từ
// ============================================

const TOPICS = [
  {
    id: 'animals',
    name: 'Animals',
    nameVi: 'Động Vật',
    icon: '🐶',
    color: '#FF9F43',
    gradient: 'linear-gradient(135deg, #FF9F43, #F7971E)',
    banner: 'banners/animals.png',
    words: [
      { en: 'Dog', vi: 'Con chó', emoji: '🐶' },
      { en: 'Cat', vi: 'Con mèo', emoji: '🐱' },
      { en: 'Bird', vi: 'Con chim', emoji: '🐦' },
      { en: 'Fish', vi: 'Con cá', emoji: '🐟' },
      { en: 'Elephant', vi: 'Con voi', emoji: '🐘' },
      { en: 'Lion', vi: 'Sư tử', emoji: '🦁' },
      { en: 'Monkey', vi: 'Con khỉ', emoji: '🐵' },
      { en: 'Rabbit', vi: 'Con thỏ', emoji: '🐰' },
      { en: 'Bear', vi: 'Con gấu', emoji: '🐻' },
      { en: 'Duck', vi: 'Con vịt', emoji: '🦆' },
    ]
  },
  {
    id: 'fruits',
    name: 'Fruits',
    nameVi: 'Trái Cây',
    icon: '🍎',
    color: '#E74C3C',
    gradient: 'linear-gradient(135deg, #E74C3C, #C0392B)',
    banner: 'banners/fruits.png',
    words: [
      { en: 'Apple', vi: 'Quả táo', emoji: '🍎' },
      { en: 'Banana', vi: 'Quả chuối', emoji: '🍌' },
      { en: 'Orange', vi: 'Quả cam', emoji: '🍊' },
      { en: 'Grape', vi: 'Quả nho', emoji: '🍇' },
      { en: 'Watermelon', vi: 'Dưa hấu', emoji: '🍉' },
      { en: 'Strawberry', vi: 'Dâu tây', emoji: '🍓' },
      { en: 'Mango', vi: 'Xoài', emoji: '🥭' },
      { en: 'Pineapple', vi: 'Dứa', emoji: '🍍' },
      { en: 'Cherry', vi: 'Quả anh đào', emoji: '🍒' },
      { en: 'Lemon', vi: 'Quả chanh', emoji: '🍋' },
    ]
  },
  {
    id: 'vegetables',
    name: 'Vegetables',
    nameVi: 'Rau Củ',
    icon: '🥕',
    color: '#27AE60',
    gradient: 'linear-gradient(135deg, #27AE60, #2ECC71)',
    words: [
      { en: 'Carrot', vi: 'Cà rốt', emoji: '🥕' },
      { en: 'Tomato', vi: 'Cà chua', emoji: '🍅' },
      { en: 'Potato', vi: 'Khoai tây', emoji: '🥔' },
      { en: 'Corn', vi: 'Ngô', emoji: '🌽' },
      { en: 'Broccoli', vi: 'Bông cải xanh', emoji: '🥦' },
      { en: 'Onion', vi: 'Hành tây', emoji: '🧅' },
      { en: 'Mushroom', vi: 'Nấm', emoji: '🍄' },
      { en: 'Pepper', vi: 'Ớt', emoji: '🌶️' },
      { en: 'Cucumber', vi: 'Dưa chuột', emoji: '🥒' },
      { en: 'Pumpkin', vi: 'Bí ngô', emoji: '🎃' },
    ]
  },
  {
    id: 'colors',
    name: 'Colors',
    nameVi: 'Màu Sắc',
    icon: '🌈',
    color: '#9B59B6',
    gradient: 'linear-gradient(135deg, #9B59B6, #8E44AD)',
    banner: 'banners/colors.png',
    words: [
      { en: 'Red', vi: 'Màu đỏ', emoji: '🔴' },
      { en: 'Blue', vi: 'Màu xanh dương', emoji: '🔵' },
      { en: 'Green', vi: 'Màu xanh lá', emoji: '🟢' },
      { en: 'Yellow', vi: 'Màu vàng', emoji: '🟡' },
      { en: 'Orange', vi: 'Màu cam', emoji: '🟠' },
      { en: 'Purple', vi: 'Màu tím', emoji: '🟣' },
      { en: 'Pink', vi: 'Màu hồng', emoji: '💗' },
      { en: 'White', vi: 'Màu trắng', emoji: '⚪' },
      { en: 'Black', vi: 'Màu đen', emoji: '⚫' },
      { en: 'Brown', vi: 'Màu nâu', emoji: '🟤' },
    ]
  },
  {
    id: 'numbers',
    name: 'Numbers',
    nameVi: 'Số Đếm',
    icon: '🔢',
    color: '#3498DB',
    gradient: 'linear-gradient(135deg, #3498DB, #2980B9)',
    words: [
      { en: 'One', vi: 'Một', emoji: '1️⃣' },
      { en: 'Two', vi: 'Hai', emoji: '2️⃣' },
      { en: 'Three', vi: 'Ba', emoji: '3️⃣' },
      { en: 'Four', vi: 'Bốn', emoji: '4️⃣' },
      { en: 'Five', vi: 'Năm', emoji: '5️⃣' },
      { en: 'Six', vi: 'Sáu', emoji: '6️⃣' },
      { en: 'Seven', vi: 'Bảy', emoji: '7️⃣' },
      { en: 'Eight', vi: 'Tám', emoji: '8️⃣' },
      { en: 'Nine', vi: 'Chín', emoji: '9️⃣' },
      { en: 'Ten', vi: 'Mười', emoji: '🔟' },
    ]
  },
  {
    id: 'body',
    name: 'Body',
    nameVi: 'Cơ Thể',
    icon: '👋',
    color: '#E67E22',
    gradient: 'linear-gradient(135deg, #E67E22, #D35400)',
    words: [
      { en: 'Head', vi: 'Đầu', emoji: '🗣️' },
      { en: 'Eye', vi: 'Mắt', emoji: '👁️' },
      { en: 'Nose', vi: 'Mũi', emoji: '👃' },
      { en: 'Mouth', vi: 'Miệng', emoji: '👄' },
      { en: 'Ear', vi: 'Tai', emoji: '👂' },
      { en: 'Hand', vi: 'Bàn tay', emoji: '✋' },
      { en: 'Foot', vi: 'Bàn chân', emoji: '🦶' },
      { en: 'Hair', vi: 'Tóc', emoji: '💇' },
      { en: 'Finger', vi: 'Ngón tay', emoji: '☝️' },
      { en: 'Leg', vi: 'Chân', emoji: '🦵' },
    ]
  },
  {
    id: 'vehicles',
    name: 'Vehicles',
    nameVi: 'Phương Tiện',
    icon: '🚗',
    color: '#1ABC9C',
    gradient: 'linear-gradient(135deg, #1ABC9C, #16A085)',
    banner: 'banners/vehicles.png',
    words: [
      { en: 'Car', vi: 'Ô tô', emoji: '🚗' },
      { en: 'Bus', vi: 'Xe buýt', emoji: '🚌' },
      { en: 'Bicycle', vi: 'Xe đạp', emoji: '🚲' },
      { en: 'Airplane', vi: 'Máy bay', emoji: '✈️' },
      { en: 'Train', vi: 'Tàu hỏa', emoji: '🚆' },
      { en: 'Boat', vi: 'Thuyền', emoji: '⛵' },
      { en: 'Helicopter', vi: 'Trực thăng', emoji: '🚁' },
      { en: 'Truck', vi: 'Xe tải', emoji: '🚚' },
      { en: 'Motorcycle', vi: 'Xe máy', emoji: '🏍️' },
      { en: 'Ambulance', vi: 'Xe cứu thương', emoji: '🚑' },
    ]
  },
  {
    id: 'food',
    name: 'Food',
    nameVi: 'Đồ Ăn',
    icon: '🍔',
    color: '#F39C12',
    gradient: 'linear-gradient(135deg, #F39C12, #E67E22)',
    banner: 'banners/food.png',
    words: [
      { en: 'Bread', vi: 'Bánh mì', emoji: '🍞' },
      { en: 'Rice', vi: 'Cơm', emoji: '🍚' },
      { en: 'Egg', vi: 'Trứng', emoji: '🥚' },
      { en: 'Milk', vi: 'Sữa', emoji: '🥛' },
      { en: 'Cheese', vi: 'Phô mai', emoji: '🧀' },
      { en: 'Cake', vi: 'Bánh ngọt', emoji: '🎂' },
      { en: 'Pizza', vi: 'Pizza', emoji: '🍕' },
      { en: 'Chicken', vi: 'Gà', emoji: '🍗' },
      { en: 'Candy', vi: 'Kẹo', emoji: '🍬' },
      { en: 'Ice Cream', vi: 'Kem', emoji: '🍦' },
    ]
  },
  {
    id: 'clothes',
    name: 'Clothes',
    nameVi: 'Quần Áo',
    icon: '👕',
    color: '#E84393',
    gradient: 'linear-gradient(135deg, #E84393, #FD79A8)',
    words: [
      { en: 'Shirt', vi: 'Áo', emoji: '👕' },
      { en: 'Pants', vi: 'Quần', emoji: '👖' },
      { en: 'Dress', vi: 'Váy đầm', emoji: '👗' },
      { en: 'Shoes', vi: 'Giày', emoji: '👟' },
      { en: 'Hat', vi: 'Mũ', emoji: '🎩' },
      { en: 'Socks', vi: 'Tất', emoji: '🧦' },
      { en: 'Jacket', vi: 'Áo khoác', emoji: '🧥' },
      { en: 'Scarf', vi: 'Khăn quàng', emoji: '🧣' },
      { en: 'Gloves', vi: 'Găng tay', emoji: '🧤' },
      { en: 'Crown', vi: 'Vương miện', emoji: '👑' },
    ]
  },
  {
    id: 'family',
    name: 'Family',
    nameVi: 'Gia Đình',
    icon: '👨‍👩‍👧',
    color: '#6C5CE7',
    gradient: 'linear-gradient(135deg, #6C5CE7, #A29BFE)',
    banner: 'banners/family.png',
    words: [
      { en: 'Mother', vi: 'Mẹ', emoji: '👩' },
      { en: 'Father', vi: 'Bố', emoji: '👨' },
      { en: 'Brother', vi: 'Anh/Em trai', emoji: '👦' },
      { en: 'Sister', vi: 'Chị/Em gái', emoji: '👧' },
      { en: 'Baby', vi: 'Em bé', emoji: '👶' },
      { en: 'Grandmother', vi: 'Bà', emoji: '👵' },
      { en: 'Grandfather', vi: 'Ông', emoji: '👴' },
      { en: 'Uncle', vi: 'Chú/Bác', emoji: '🧔' },
      { en: 'Aunt', vi: 'Cô/Dì', emoji: '👩‍🦰' },
      { en: 'Family', vi: 'Gia đình', emoji: '👨‍👩‍👧‍👦' },
    ]
  },
  {
    id: 'weather',
    name: 'Weather',
    nameVi: 'Thời Tiết',
    icon: '☀️',
    color: '#00B894',
    gradient: 'linear-gradient(135deg, #00B894, #00CEC9)',
    words: [
      { en: 'Sun', vi: 'Mặt trời', emoji: '☀️' },
      { en: 'Rain', vi: 'Mưa', emoji: '🌧️' },
      { en: 'Cloud', vi: 'Mây', emoji: '☁️' },
      { en: 'Wind', vi: 'Gió', emoji: '💨' },
      { en: 'Snow', vi: 'Tuyết', emoji: '❄️' },
      { en: 'Rainbow', vi: 'Cầu vồng', emoji: '🌈' },
      { en: 'Storm', vi: 'Bão', emoji: '⛈️' },
      { en: 'Moon', vi: 'Mặt trăng', emoji: '🌙' },
      { en: 'Star', vi: 'Ngôi sao', emoji: '⭐' },
      { en: 'Lightning', vi: 'Sét', emoji: '⚡' },
    ]
  },
  {
    id: 'house',
    name: 'House',
    nameVi: 'Đồ Trong Nhà',
    icon: '🏠',
    color: '#FDCB6E',
    gradient: 'linear-gradient(135deg, #FDCB6E, #F9CA24)',
    words: [
      { en: 'Table', vi: 'Cái bàn', emoji: '🪑' },
      { en: 'Chair', vi: 'Cái ghế', emoji: '💺' },
      { en: 'Bed', vi: 'Giường', emoji: '🛏️' },
      { en: 'Door', vi: 'Cửa', emoji: '🚪' },
      { en: 'Window', vi: 'Cửa sổ', emoji: '🪟' },
      { en: 'Lamp', vi: 'Đèn', emoji: '💡' },
      { en: 'Clock', vi: 'Đồng hồ', emoji: '🕐' },
      { en: 'Television', vi: 'Ti vi', emoji: '📺' },
      { en: 'Telephone', vi: 'Điện thoại', emoji: '📱' },
      { en: 'Book', vi: 'Quyển sách', emoji: '📚' },
    ]
  },
  {
    id: 'school',
    name: 'School',
    nameVi: 'Trường Học',
    icon: '🎒',
    color: '#0984E3',
    gradient: 'linear-gradient(135deg, #0984E3, #74B9FF)',
    words: [
      { en: 'Pencil', vi: 'Bút chì', emoji: '✏️' },
      { en: 'Book', vi: 'Sách', emoji: '📖' },
      { en: 'Ruler', vi: 'Thước kẻ', emoji: '📏' },
      { en: 'Eraser', vi: 'Cục tẩy', emoji: '🧹' },
      { en: 'Bag', vi: 'Cặp sách', emoji: '🎒' },
      { en: 'Teacher', vi: 'Cô giáo', emoji: '👩‍🏫' },
      { en: 'Student', vi: 'Học sinh', emoji: '👩‍🎓' },
      { en: 'Crayon', vi: 'Bút sáp màu', emoji: '🖍️' },
      { en: 'Scissors', vi: 'Kéo', emoji: '✂️' },
      { en: 'Globe', vi: 'Quả địa cầu', emoji: '🌍' },
    ]
  },
  {
    id: 'insects',
    name: 'Insects',
    nameVi: 'Côn Trùng',
    icon: '🦋',
    color: '#A3CB38',
    gradient: 'linear-gradient(135deg, #A3CB38, #C4E538)',
    words: [
      { en: 'Butterfly', vi: 'Bướm', emoji: '🦋' },
      { en: 'Bee', vi: 'Con ong', emoji: '🐝' },
      { en: 'Ant', vi: 'Con kiến', emoji: '🐜' },
      { en: 'Spider', vi: 'Nhện', emoji: '🕷️' },
      { en: 'Ladybug', vi: 'Bọ rùa', emoji: '🐞' },
      { en: 'Snail', vi: 'Ốc sên', emoji: '🐌' },
      { en: 'Worm', vi: 'Giun', emoji: '🪱' },
      { en: 'Mosquito', vi: 'Muỗi', emoji: '🦟' },
      { en: 'Fly', vi: 'Ruồi', emoji: '🪰' },
      { en: 'Cricket', vi: 'Dế', emoji: '🦗' },
    ]
  },
  {
    id: 'sports',
    name: 'Sports',
    nameVi: 'Thể Thao',
    icon: '⚽',
    color: '#00B5AD',
    gradient: 'linear-gradient(135deg, #00B5AD, #21D4FD)',
    words: [
      { en: 'Soccer', vi: 'Bóng đá', emoji: '⚽' },
      { en: 'Basketball', vi: 'Bóng rổ', emoji: '🏀' },
      { en: 'Swimming', vi: 'Bơi lội', emoji: '🏊' },
      { en: 'Running', vi: 'Chạy bộ', emoji: '🏃' },
      { en: 'Tennis', vi: 'Quần vợt', emoji: '🎾' },
      { en: 'Baseball', vi: 'Bóng chày', emoji: '⚾' },
      { en: 'Cycling', vi: 'Đạp xe', emoji: '🚴' },
      { en: 'Dancing', vi: 'Nhảy múa', emoji: '💃' },
      { en: 'Surfing', vi: 'Lướt sóng', emoji: '🏄' },
      { en: 'Martial Arts', vi: 'Võ thuật', emoji: '🥋' },
    ]
  },
];
