// Bộ câu hỏi mặc định — bám theo các chủ đề chương trình Tiếng Anh lớp 4
// (Global Success / Family and Friends — chương trình GDPT 2018)
// Định dạng: t = chủ đề, q = câu hỏi, o = 4 đáp án, a = chỉ số đáp án đúng (0-3),
//            s = văn bản đọc loa (tuỳ chọn), e = giải thích khi trả lời sai

const TOPICS = {
  t1: { name: "Bản thân & bạn bè", icon: "🙋" },
  t2: { name: "Ngày tháng & thời gian", icon: "🕐" },
  t3: { name: "Trường học & môn học", icon: "🏫" },
  t4: { name: "Hoạt động hằng ngày", icon: "🌞" },
  t5: { name: "Khả năng (can/can't)", icon: "💪" },
  t6: { name: "Gia đình & nghề nghiệp", icon: "👨‍👩‍👧" },
  t7: { name: "Đồ ăn & thức uống", icon: "🍎" },
  t8: { name: "Động vật", icon: "🐘" },
  t9: { name: "Ngoại hình & quần áo", icon: "👕" },
  t10: { name: "Nơi chốn & lễ hội", icon: "🎉" },
};

const QUESTION_BANK = [
  // ===== T1: Bản thân & bạn bè =====
  { t: "t1", q: "Hello. My name ___ Nam.", o: ["is", "am", "are", "be"], a: 0, s: "Hello. My name is Nam.", e: "\"My name\" là ngôi thứ 3 số ít nên dùng \"is\": My name is Nam." },
  { t: "t1", q: "Hi, I'm Linda. I'm from ___ (nước Anh).", o: ["Japan", "England", "Vietnam", "America"], a: 1, s: "I'm from England.", e: "Nước Anh = England. (Japan = Nhật, Vietnam = Việt Nam, America = Mỹ)" },
  { t: "t1", q: "\"Where are you from?\" — \"___\"", o: ["I'm nine years old.", "I'm from Vietnam.", "My name is Mai.", "It's a book."], a: 1, s: "Where are you from?", e: "\"Where are you from?\" hỏi bạn đến từ đâu → trả lời \"I'm from + tên nước\"." },
  { t: "t1", q: "\"How old are you?\" — \"___\"", o: ["I'm fine.", "I'm from Japan.", "I'm ten years old.", "Nice to meet you."], a: 2, s: "How old are you?", e: "\"How old are you?\" hỏi tuổi → trả lời \"I'm + số tuổi + years old\"." },
  { t: "t1", q: "\"Nice to meet you.\" — \"___\"", o: ["Nice to meet you, too.", "I'm nine.", "Goodbye.", "Thank you very much."], a: 0, s: "Nice to meet you.", e: "Khi ai đó nói \"Rất vui được gặp bạn\", mình đáp lại \"Nice to meet you, too\" (Mình cũng vậy)." },
  { t: "t1", q: "Tony is from America. He is ___.", o: ["Vietnamese", "Japanese", "English", "American"], a: 3, s: "Tony is from America. He is American.", e: "Đến từ America (Mỹ) thì quốc tịch là American (người Mỹ)." },
  { t: "t1", q: "Từ nào có nghĩa là \"bạn bè\"?", o: ["family", "friends", "teacher", "student"], a: 1, s: "friends", e: "friends = bạn bè. (family = gia đình, teacher = giáo viên, student = học sinh)" },
  { t: "t1", q: "Akiko is from Japan. She is ___.", o: ["Japanese", "American", "English", "Australian"], a: 0, s: "Akiko is from Japan. She is Japanese.", e: "Đến từ Japan (Nhật Bản) thì quốc tịch là Japanese (người Nhật)." },
  { t: "t1", q: "\"What's your name?\" — \"___\"", o: ["I'm from Ha Noi.", "My name is Phong.", "I'm fine, thanks.", "It's Monday."], a: 1, s: "What's your name?", e: "\"What's your name?\" hỏi tên → trả lời \"My name is + tên\"." },
  { t: "t1", q: "\"How are you?\" — \"___\"", o: ["I'm ten.", "I'm fine, thank you.", "I'm a student.", "Goodbye."], a: 1, s: "How are you?", e: "\"How are you?\" hỏi thăm sức khoẻ → trả lời \"I'm fine, thank you\"." },
  { t: "t1", q: "Chọn câu chào buổi sáng:", o: ["Good night.", "Good morning.", "Goodbye.", "Good luck."], a: 1, s: "Good morning.", e: "Good morning = chào buổi sáng. (Good night = chúc ngủ ngon, Goodbye = tạm biệt, Good luck = chúc may mắn)" },
  { t: "t1", q: "Linda is from Australia. She speaks ___.", o: ["Vietnamese", "Japanese", "English", "Chinese"], a: 2, s: "She speaks English.", e: "Người Úc (Australia) nói tiếng Anh (English)." },
  { t: "t1", q: "\"Goodbye!\" — \"___\"", o: ["Hello!", "See you later!", "Good morning!", "Nice to meet you!"], a: 1, s: "Goodbye. See you later.", e: "Khi tạm biệt, đáp lại \"See you later!\" (Hẹn gặp lại!)." },
  { t: "t1", q: "I ___ a pupil at Nguyen Du Primary School.", o: ["is", "are", "am", "be"], a: 2, s: "I am a pupil.", e: "Chủ ngữ \"I\" luôn đi với \"am\": I am..." },
  { t: "t1", q: "\"nationality\" có nghĩa là gì?", o: ["quốc tịch", "tên", "tuổi", "địa chỉ"], a: 0, s: "nationality", e: "nationality = quốc tịch." },

  // ===== T2: Ngày tháng & thời gian =====
  { t: "t2", q: "\"What day is it today?\" — \"It's ___.\"", o: ["September", "Monday", "nine o'clock", "2026"], a: 1, s: "What day is it today? It's Monday.", e: "\"What day...?\" hỏi thứ trong tuần → trả lời bằng thứ (Monday). September là tháng, nine o'clock là giờ." },
  { t: "t2", q: "Thứ Tư trong tiếng Anh là:", o: ["Tuesday", "Thursday", "Wednesday", "Sunday"], a: 2, s: "Wednesday", e: "Wednesday = thứ Tư. Cẩn thận: Tuesday = thứ Ba, Thursday = thứ Năm." },
  { t: "t2", q: "We have English on Mondays and ___.  (thứ Sáu)", o: ["Fridays", "Sundays", "Tuesdays", "Saturdays"], a: 0, s: "We have English on Mondays and Fridays.", e: "Thứ Sáu = Friday." },
  { t: "t2", q: "\"What time is it?\" — \"It's seven ___.\"", o: ["hours", "o'clock", "times", "minutes"], a: 1, s: "What time is it? It's seven o'clock.", e: "Giờ đúng (7:00) nói là \"seven o'clock\"." },
  { t: "t2", q: "Tháng 12 trong tiếng Anh là:", o: ["November", "October", "December", "September"], a: 2, s: "December", e: "December = tháng 12. (November = tháng 11, October = tháng 10, September = tháng 9)" },
  { t: "t2", q: "\"When is your birthday?\" — \"It's ___ May.\"", o: ["on", "at", "in", "to"], a: 2, s: "When is your birthday? It's in May.", e: "Trước tháng (May, June...) dùng giới từ \"in\": in May." },
  { t: "t2", q: "It's 7.15. = It's a quarter ___ seven.", o: ["to", "past", "at", "on"], a: 1, s: "It's a quarter past seven.", e: "7 giờ 15 = a quarter past seven (\"past\" = sau giờ đó 15 phút; \"to\" dùng khi kém)." },
  { t: "t2", q: "Một tuần có bao nhiêu ngày? \"There are ___ days in a week.\"", o: ["five", "six", "seven", "eight"], a: 2, s: "There are seven days in a week.", e: "Một tuần có 7 ngày → seven." },
  { t: "t2", q: "Hôm nay là thứ Bảy. Ngày mai là ___.", o: ["Friday", "Sunday", "Monday", "Saturday"], a: 1, s: "Today is Saturday. Tomorrow is Sunday.", e: "Sau thứ Bảy (Saturday) là Chủ nhật (Sunday)." },
  { t: "t2", q: "Tháng nào có Tết Trung thu (tháng 9 hoặc 10)? \"It's in ___ or October.\"", o: ["September", "December", "January", "March"], a: 0, s: "September", e: "Tết Trung thu vào tháng 9 (September) hoặc tháng 10 (October)." },
  { t: "t2", q: "It's 6.30. = It's half ___ six.", o: ["to", "at", "past", "in"], a: 2, s: "It's half past six.", e: "6 giờ 30 = half past six (\"half past\" = giờ rưỡi)." },
  { t: "t2", q: "\"What's the date today?\" — \"It's the ___ of June.\"", o: ["two", "second", "twice", "too"], a: 1, s: "It's the second of June.", e: "Ngày trong tháng dùng số thứ tự: second (mùng 2), không dùng số đếm \"two\"." },
  { t: "t2", q: "Tháng đầu tiên của năm là:", o: ["February", "December", "January", "March"], a: 2, s: "January", e: "January = tháng 1, tháng đầu tiên của năm." },
  { t: "t2", q: "I go to school ___ Monday to Friday.", o: ["from", "at", "in", "on"], a: 0, s: "I go to school from Monday to Friday.", e: "Cấu trúc \"from... to...\" = từ... đến...: from Monday to Friday." },
  { t: "t2", q: "\"tomorrow\" có nghĩa là gì?", o: ["hôm qua", "hôm nay", "ngày mai", "tuần trước"], a: 2, s: "tomorrow", e: "tomorrow = ngày mai. (yesterday = hôm qua, today = hôm nay)" },

  // ===== T3: Trường học & môn học =====
  { t: "t3", q: "\"What subjects do you have today?\" — \"I have ___ and English.\"", o: ["Maths", "football", "milk", "Monday"], a: 0, s: "I have Maths and English.", e: "Câu hỏi về môn học (subjects) → trả lời bằng tên môn học: Maths (Toán)." },
  { t: "t3", q: "Môn Tiếng Việt trong tiếng Anh là:", o: ["Science", "Vietnamese", "Music", "Art"], a: 1, s: "Vietnamese", e: "Vietnamese = môn Tiếng Việt. (Science = Khoa học, Music = Âm nhạc, Art = Mĩ thuật)" },
  { t: "t3", q: "I like ___ because I like drawing pictures.", o: ["Music", "Maths", "Art", "PE"], a: 2, s: "I like Art because I like drawing pictures.", e: "Thích vẽ tranh (drawing pictures) thì thích môn Mĩ thuật (Art)." },
  { t: "t3", q: "\"school library\" là nơi để làm gì?", o: ["ăn trưa", "đọc sách", "chơi bóng", "ngủ trưa"], a: 1, s: "library", e: "library = thư viện, nơi để đọc sách." },
  { t: "t3", q: "We play sports and games in ___ lessons.", o: ["Music", "Maths", "Science", "PE"], a: 3, s: "We play sports in PE lessons.", e: "PE (Physical Education) = môn Thể dục, giờ học chơi thể thao." },
  { t: "t3", q: "\"May I come in?\" nghĩa là gì?", o: ["Em có thể ra ngoài không?", "Em có thể vào lớp không?", "Em có thể mượn bút không?", "Em có thể uống nước không?"], a: 1, s: "May I come in?", e: "come in = đi vào → \"May I come in?\" = Em có thể vào lớp không?" },
  { t: "t3", q: "I write with a ___.", o: ["ruler", "pen", "bag", "desk"], a: 1, s: "I write with a pen.", e: "Viết (write) bằng bút (pen). Ruler = thước kẻ để kẻ, không để viết." },
  { t: "t3", q: "\"classroom\" có nghĩa là:", o: ["sân trường", "thư viện", "phòng học", "căng tin"], a: 2, s: "classroom", e: "classroom = phòng học (class = lớp + room = phòng)." },
  { t: "t3", q: "In ___ lessons, we sing songs.", o: ["Music", "Maths", "Science", "History"], a: 0, s: "In Music lessons, we sing songs.", e: "Hát (sing songs) là hoạt động của giờ Âm nhạc (Music)." },
  { t: "t3", q: "\"What class are you in?\" — \"I'm in class ___.\"", o: ["4A", "at home", "Monday", "seven o'clock"], a: 0, s: "What class are you in? I'm in class 4A.", e: "\"What class...?\" hỏi lớp nào → trả lời bằng tên lớp: class 4A." },
  { t: "t3", q: "Cái cặp sách trong tiếng Anh là:", o: ["notebook", "school bag", "pencil case", "rubber"], a: 1, s: "school bag", e: "school bag = cặp sách. (notebook = vở, pencil case = hộp bút, rubber = cục tẩy)" },
  { t: "t3", q: "I have Maths ___ Tuesdays.", o: ["in", "at", "on", "to"], a: 2, s: "I have Maths on Tuesdays.", e: "Trước thứ trong tuần (Monday, Tuesday...) dùng giới từ \"on\": on Tuesdays." },
  { t: "t3", q: "\"May I go out?\" — Cô giáo đồng ý sẽ nói: \"___\"", o: ["No, thanks.", "Yes, you can.", "I'm sorry.", "Me too."], a: 1, s: "May I go out? Yes, you can.", e: "Đồng ý cho phép → \"Yes, you can\" (Được, em có thể)." },
  { t: "t3", q: "We do sums (làm phép tính) in ___ lessons.", o: ["Art", "Maths", "Music", "English"], a: 1, s: "We do sums in Maths lessons.", e: "Làm phép tính (do sums) là hoạt động của giờ Toán (Maths)." },
  { t: "t3", q: "\"timetable\" có nghĩa là:", o: ["thời khoá biểu", "bài kiểm tra", "bài tập về nhà", "kỳ nghỉ"], a: 0, s: "timetable", e: "timetable = thời khoá biểu (time = thời gian + table = bảng)." },

  // ===== T4: Hoạt động hằng ngày =====
  { t: "t4", q: "I ___ up at six o'clock every morning.", o: ["go", "get", "do", "have"], a: 1, s: "I get up at six o'clock every morning.", e: "get up = thức dậy. Cụm từ cố định, không dùng go/do/have." },
  { t: "t4", q: "She ___ her homework in the evening.", o: ["do", "dos", "does", "doing"], a: 2, s: "She does her homework in the evening.", e: "Chủ ngữ \"She\" (ngôi 3 số ít) → động từ thêm -es: does." },
  { t: "t4", q: "\"brush my teeth\" nghĩa là:", o: ["rửa mặt", "chải tóc", "đánh răng", "tắm"], a: 2, s: "I brush my teeth.", e: "brush my teeth = đánh răng (brush = chải, teeth = răng)." },
  { t: "t4", q: "I have ___ at 7 a.m. before going to school.", o: ["dinner", "lunch", "breakfast", "bedtime"], a: 2, s: "I have breakfast at seven a.m.", e: "Bữa ăn lúc 7 giờ sáng trước khi đi học là bữa sáng (breakfast)." },
  { t: "t4", q: "\"What do you do in the afternoon?\" — \"I ___ football with my friends.\"", o: ["play", "plays", "playing", "played"], a: 0, s: "I play football with my friends.", e: "Chủ ngữ \"I\" → động từ giữ nguyên: I play." },
  { t: "t4", q: "He ___ TV after dinner.", o: ["watch", "watches", "watching", "watchs"], a: 1, s: "He watches TV after dinner.", e: "Chủ ngữ \"He\" (ngôi 3 số ít), động từ tận cùng -ch thêm -es: watches." },
  { t: "t4", q: "I go to ___ at nine o'clock at night.", o: ["school", "bed", "lunch", "work"], a: 1, s: "I go to bed at nine o'clock.", e: "go to bed = đi ngủ. 9 giờ tối (at night) là giờ đi ngủ." },
  { t: "t4", q: "\"listen to music\" nghĩa là:", o: ["xem phim", "nghe nhạc", "đọc truyện", "vẽ tranh"], a: 1, s: "I listen to music.", e: "listen to music = nghe nhạc (listen = nghe, music = nhạc)." },
  { t: "t4", q: "My hobby is ___ books.", o: ["reading", "read", "reads", "to reading"], a: 0, s: "My hobby is reading books.", e: "Sau \"My hobby is\" dùng động từ thêm -ing: reading books (sở thích là đọc sách)." },
  { t: "t4", q: "\"What do you do on Sundays?\" — \"___\"", o: ["I'm nine years old.", "I visit my grandparents.", "It's Sunday.", "Yes, I do."], a: 1, s: "What do you do on Sundays?", e: "Câu hỏi \"bạn làm gì vào Chủ nhật?\" → trả lời bằng hoạt động: I visit my grandparents (thăm ông bà)." },
  { t: "t4", q: "In the morning, I wash my ___.", o: ["book", "face", "bag", "shoes"], a: 1, s: "I wash my face.", e: "wash my face = rửa mặt — việc làm buổi sáng." },
  { t: "t4", q: "They ___ badminton every afternoon.", o: ["plays", "playing", "play", "to play"], a: 2, s: "They play badminton every afternoon.", e: "Chủ ngữ \"They\" (số nhiều) → động từ giữ nguyên: play." },
  { t: "t4", q: "\"fly a kite\" nghĩa là:", o: ["thả diều", "đá bóng", "bơi lội", "nhảy dây"], a: 0, s: "fly a kite", e: "fly a kite = thả diều (fly = bay, kite = con diều)." },
  { t: "t4", q: "I often help my mother ___ the housework.", o: ["at", "with", "on", "for"], a: 1, s: "I help my mother with the housework.", e: "help + ai + with + việc gì: help my mother with the housework (giúp mẹ việc nhà)." },
  { t: "t4", q: "\"go swimming\" nghĩa là:", o: ["đi câu cá", "đi bộ", "đi bơi", "đi học"], a: 2, s: "go swimming", e: "go swimming = đi bơi (swim = bơi)." },

  // ===== T5: Khả năng (can/can't) =====
  { t: "t5", q: "\"Can you swim?\" — \"Yes, I ___.\"", o: ["can't", "can", "do", "am"], a: 1, s: "Can you swim? Yes, I can.", e: "Câu hỏi với \"Can\" → trả lời Yes, I can / No, I can't." },
  { t: "t5", q: "I can ___ a bike.", o: ["ride", "riding", "rides", "to ride"], a: 0, s: "I can ride a bike.", e: "Sau \"can\" dùng động từ nguyên thể (không thêm gì): can ride." },
  { t: "t5", q: "She can't ___ the piano.", o: ["plays", "playing", "play", "played"], a: 2, s: "She can't play the piano.", e: "Sau \"can't\" dùng động từ nguyên thể: can't play." },
  { t: "t5", q: "\"Can your brother cook?\" — \"No, he ___.\"", o: ["can", "isn't", "don't", "can't"], a: 3, s: "Can your brother cook? No, he can't.", e: "Trả lời phủ định câu hỏi \"Can...?\" → No, he can't." },
  { t: "t5", q: "A bird can ___.", o: ["swim", "fly", "drive", "cook"], a: 1, s: "A bird can fly.", e: "Chim (bird) biết bay (fly)." },
  { t: "t5", q: "\"dance\" có nghĩa là:", o: ["hát", "múa/nhảy", "vẽ", "bơi"], a: 1, s: "dance", e: "dance = múa/nhảy. (sing = hát, draw = vẽ, swim = bơi)" },
  { t: "t5", q: "I can sing but I ___ dance.", o: ["can", "can't", "am", "do"], a: 1, s: "I can sing but I can't dance.", e: "\"but\" (nhưng) chỉ sự trái ngược: biết hát NHƯNG không biết nhảy → can't." },
  { t: "t5", q: "\"What can you do?\" — \"___\"", o: ["I can play the guitar.", "I like fish.", "Yes, I can.", "It's a cat."], a: 0, s: "What can you do? I can play the guitar.", e: "\"What can you do?\" hỏi bạn biết làm gì → trả lời \"I can + việc làm được\"." },
  { t: "t5", q: "Fish can ___ but they can't walk.", o: ["fly", "run", "swim", "jump"], a: 2, s: "Fish can swim but they can't walk.", e: "Cá (fish) biết bơi (swim) nhưng không biết đi bộ." },
  { t: "t5", q: "He can play ___ guitar.", o: ["a", "an", "the", "some"], a: 2, s: "He can play the guitar.", e: "Chơi nhạc cụ luôn dùng \"the\": play the guitar, play the piano." },
  { t: "t5", q: "\"skip\" (nhảy dây) — Mai can ___ very well.", o: ["skip", "skips", "skipping", "to skip"], a: 0, s: "Mai can skip very well.", e: "Sau \"can\" dùng động từ nguyên thể: can skip." },
  { t: "t5", q: "\"Can Linda speak Vietnamese?\" — \"Yes, ___ can.\"", o: ["he", "she", "it", "they"], a: 1, s: "Can Linda speak Vietnamese? Yes, she can.", e: "Linda là con gái → thay bằng \"she\": Yes, she can." },
  { t: "t5", q: "An elephant ___ fly.", o: ["can", "can't", "is", "does"], a: 1, s: "An elephant can't fly.", e: "Voi không biết bay → dùng phủ định \"can't\"." },
  { t: "t5", q: "\"draw a picture\" nghĩa là:", o: ["chụp ảnh", "vẽ một bức tranh", "viết một lá thư", "đọc một cuốn sách"], a: 1, s: "draw a picture", e: "draw a picture = vẽ một bức tranh (draw = vẽ, picture = bức tranh)." },
  { t: "t5", q: "I can swim, ___ my little sister can't.", o: ["but", "and", "or", "so"], a: 0, s: "I can swim, but my little sister can't.", e: "Hai vế trái ngược nhau (mình biết bơi, em gái không) → nối bằng \"but\" (nhưng)." },

  // ===== T6: Gia đình & nghề nghiệp =====
  { t: "t6", q: "\"What does your father do?\" — \"He's a ___.\"", o: ["doctor", "hospital", "kitchen", "Monday"], a: 0, s: "What does your father do? He's a doctor.", e: "\"What does... do?\" hỏi nghề nghiệp → trả lời bằng nghề: doctor (bác sĩ). Hospital là nơi làm việc, không phải nghề." },
  { t: "t6", q: "My mother is a teacher. She works in a ___.", o: ["hospital", "school", "field", "factory"], a: 1, s: "My mother is a teacher. She works in a school.", e: "Giáo viên (teacher) làm việc ở trường học (school)." },
  { t: "t6", q: "\"farmer\" có nghĩa là:", o: ["bác sĩ", "công nhân", "nông dân", "y tá"], a: 2, s: "farmer", e: "farmer = nông dân (farm = nông trại). (doctor = bác sĩ, worker = công nhân, nurse = y tá)" },
  { t: "t6", q: "A ___ works in a hospital and helps sick people.", o: ["nurse", "singer", "driver", "farmer"], a: 0, s: "A nurse works in a hospital.", e: "Y tá (nurse) làm ở bệnh viện, chăm sóc người ốm (sick people)." },
  { t: "t6", q: "\"How many people are there in your family?\" — \"There ___ four people.\"", o: ["is", "are", "am", "be"], a: 1, s: "There are four people in my family.", e: "\"four people\" là số nhiều → dùng \"There are\"." },
  { t: "t6", q: "My father's mother is my ___.", o: ["aunt", "sister", "grandmother", "mother"], a: 2, s: "My father's mother is my grandmother.", e: "Mẹ của bố là bà nội (grandmother)." },
  { t: "t6", q: "\"uncle\" có nghĩa là:", o: ["chú/bác/cậu", "cô/dì", "anh trai", "ông nội"], a: 0, s: "uncle", e: "uncle = chú/bác/cậu. (aunt = cô/dì, brother = anh trai, grandfather = ông)" },
  { t: "t6", q: "He drives a taxi. He is a ___.", o: ["farmer", "driver", "worker", "dentist"], a: 1, s: "He drives a taxi. He is a driver.", e: "Người lái xe (drive) là tài xế (driver)." },
  { t: "t6", q: "My sister ___ a student.", o: ["am", "are", "is", "be"], a: 2, s: "My sister is a student.", e: "\"My sister\" là ngôi 3 số ít → dùng \"is\"." },
  { t: "t6", q: "A ___ works in a field and grows rice.", o: ["doctor", "singer", "pilot", "farmer"], a: 3, s: "A farmer works in a field and grows rice.", e: "Nông dân (farmer) làm việc trên cánh đồng (field) và trồng lúa (grow rice)." },
  { t: "t6", q: "\"Where does your mother work?\" — \"She works in a ___.\" (nhà máy)", o: ["factory", "field", "school", "library"], a: 0, s: "She works in a factory.", e: "Nhà máy = factory. (field = cánh đồng, school = trường, library = thư viện)" },
  { t: "t6", q: "\"family\" có nghĩa là:", o: ["bạn bè", "gia đình", "hàng xóm", "lớp học"], a: 1, s: "family", e: "family = gia đình." },
  { t: "t6", q: "My brother wants to be a ___ because he likes flying planes.", o: ["pilot", "cook", "dentist", "farmer"], a: 0, s: "He wants to be a pilot.", e: "Thích lái máy bay (flying planes) → muốn làm phi công (pilot)." },
  { t: "t6", q: "A cook works in a ___.", o: ["hospital", "kitchen", "library", "garden"], a: 1, s: "A cook works in a kitchen.", e: "Đầu bếp (cook) làm việc trong bếp (kitchen)." },
  { t: "t6", q: "\"What does your aunt do?\" — \"___\"", o: ["She's in the kitchen.", "She's a nurse.", "She's nine.", "Yes, she does."], a: 1, s: "What does your aunt do? She's a nurse.", e: "\"What does... do?\" hỏi nghề nghiệp → trả lời bằng nghề: She's a nurse (cô ấy là y tá)." },

  // ===== T7: Đồ ăn & thức uống =====
  { t: "t7", q: "\"What's your favourite food?\" — \"It's ___.\"", o: ["orange juice", "fried chicken", "Monday", "blue"], a: 1, s: "What's your favourite food? It's fried chicken.", e: "Hỏi về món ăn (food) → trả lời bằng đồ ăn: fried chicken (gà rán). Orange juice là đồ uống." },
  { t: "t7", q: "\"milk\" có nghĩa là:", o: ["nước cam", "sữa", "trà", "nước lọc"], a: 1, s: "milk", e: "milk = sữa. (orange juice = nước cam, tea = trà, water = nước lọc)" },
  { t: "t7", q: "I'd like some rice and ___, please. (cá)", o: ["fish", "book", "water", "juice"], a: 0, s: "I'd like some rice and fish, please.", e: "Cá = fish." },
  { t: "t7", q: "\"Would you like some milk?\" — \"___\"", o: ["Yes, please.", "I'm ten.", "It's Monday.", "She's my mother."], a: 0, s: "Would you like some milk? Yes, please.", e: "Được mời \"Would you like...?\" → nhận lời lịch sự: \"Yes, please\" (Dạ có ạ)." },
  { t: "t7", q: "\"beef\" có nghĩa là:", o: ["thịt gà", "thịt lợn", "thịt bò", "tôm"], a: 2, s: "beef", e: "beef = thịt bò. (chicken = thịt gà, pork = thịt lợn, shrimp = tôm)" },
  { t: "t7", q: "My favourite drink is orange ___.", o: ["rice", "juice", "bread", "noodles"], a: 1, s: "My favourite drink is orange juice.", e: "orange juice = nước cam — là đồ uống (drink). Rice, bread, noodles là đồ ăn." },
  { t: "t7", q: "\"vegetables\" có nghĩa là:", o: ["trái cây", "rau củ", "kẹo bánh", "đồ uống"], a: 1, s: "vegetables", e: "vegetables = rau củ. (fruit = trái cây)" },
  { t: "t7", q: "\"What would you like to eat?\" — \"___\"", o: ["I'd like a bowl of noodles.", "I like blue.", "Yes, I would.", "It's eight o'clock."], a: 0, s: "What would you like to eat? I'd like a bowl of noodles.", e: "Hỏi muốn ăn gì → trả lời \"I'd like + món ăn\": a bowl of noodles (một bát mì)." },
  { t: "t7", q: "Bánh mì trong tiếng Anh là:", o: ["rice", "noodles", "bread", "soup"], a: 2, s: "bread", e: "bread = bánh mì. (rice = cơm, noodles = mì/bún, soup = súp/canh)" },
  { t: "t7", q: "\"a glass of ___\" — chọn từ phù hợp:", o: ["water", "bread", "chicken", "rice"], a: 0, s: "a glass of water", e: "a glass of (một cốc) đi với đồ uống: a glass of water (một cốc nước)." },
  { t: "t7", q: "\"hungry\" có nghĩa là:", o: ["khát", "đói", "no", "mệt"], a: 1, s: "I'm hungry.", e: "hungry = đói. (thirsty = khát, full = no, tired = mệt)" },
  { t: "t7", q: "\"Do you like bananas?\" — \"No, I ___.\"", o: ["do", "don't", "can't", "am not"], a: 1, s: "Do you like bananas? No, I don't.", e: "Câu hỏi với \"Do you...?\" → trả lời phủ định: No, I don't." },
  { t: "t7", q: "I'm thirsty. I'd like some ___.", o: ["rice", "chicken", "water", "bread"], a: 2, s: "I'm thirsty. I'd like some water.", e: "thirsty = khát nước → cần uống nước (water), không phải đồ ăn." },
  { t: "t7", q: "\"grapes\" có nghĩa là:", o: ["quả nho", "quả táo", "quả cam", "quả chuối"], a: 0, s: "grapes", e: "grapes = quả nho. (apple = táo, orange = cam, banana = chuối)" },
  { t: "t7", q: "She likes ___ very much. (kem)", o: ["ice cream", "hot dog", "salad", "soup"], a: 0, s: "She likes ice cream very much.", e: "Kem = ice cream." },

  // ===== T8: Động vật =====
  { t: "t8", q: "\"elephant\" có nghĩa là:", o: ["con hổ", "con voi", "con khỉ", "con gấu"], a: 1, s: "elephant", e: "elephant = con voi. (tiger = hổ, monkey = khỉ, bear = gấu)" },
  { t: "t8", q: "Let's go to the ___ to see the animals.", o: ["zoo", "school", "kitchen", "library"], a: 0, s: "Let's go to the zoo to see the animals.", e: "Muốn xem động vật (animals) thì đến sở thú (zoo)." },
  { t: "t8", q: "A ___ is the king of the jungle.", o: ["rabbit", "lion", "duck", "cat"], a: 1, s: "A lion is the king of the jungle.", e: "Sư tử (lion) được gọi là chúa tể rừng xanh (king of the jungle)." },
  { t: "t8", q: "\"monkey\" có nghĩa là:", o: ["con vẹt", "con hươu", "con khỉ", "con cá sấu"], a: 2, s: "monkey", e: "monkey = con khỉ. (parrot = vẹt, deer = hươu, crocodile = cá sấu)" },
  { t: "t8", q: "I like ___ because they are very fast. (con ngựa)", o: ["horses", "snails", "turtles", "chickens"], a: 0, s: "I like horses because they are very fast.", e: "Con ngựa = horse; ngựa chạy rất nhanh (fast)." },
  { t: "t8", q: "\"Do you like tigers?\" — \"Yes, I ___.\"", o: ["don't", "do", "can", "am"], a: 1, s: "Do you like tigers? Yes, I do.", e: "Câu hỏi \"Do you...?\" → trả lời khẳng định: Yes, I do." },
  { t: "t8", q: "A giraffe has a long ___.", o: ["neck", "ear", "hand", "foot"], a: 0, s: "A giraffe has a long neck.", e: "Hươu cao cổ (giraffe) có cái cổ (neck) dài." },
  { t: "t8", q: "\"bear\" có nghĩa là:", o: ["con sói", "con gấu", "con cáo", "con rắn"], a: 1, s: "bear", e: "bear = con gấu. (wolf = sói, fox = cáo, snake = rắn)" },
  { t: "t8", q: "Monkeys like eating ___.", o: ["bananas", "books", "fish sauce", "bread"], a: 0, s: "Monkeys like eating bananas.", e: "Khỉ (monkeys) thích ăn chuối (bananas)." },
  { t: "t8", q: "\"crocodile\" có nghĩa là:", o: ["con cá heo", "con cá sấu", "con rùa", "con ếch"], a: 1, s: "crocodile", e: "crocodile = con cá sấu. (dolphin = cá heo, turtle = rùa, frog = ếch)" },
  { t: "t8", q: "I don't like snakes because they are ___.", o: ["beautiful", "scary", "friendly", "funny"], a: 1, s: "I don't like snakes because they are scary.", e: "Không thích (don't like) rắn vì chúng đáng sợ (scary)." },
  { t: "t8", q: "\"Why do you like monkeys?\" — \"Because they are ___.\"", o: ["funny", "Monday", "hungry", "ten"], a: 0, s: "Because they are funny.", e: "\"Why...?\" (tại sao) → trả lời \"Because...\" + lý do: funny (vui nhộn)." },
  { t: "t8", q: "A ___ can say hello. (con vẹt)", o: ["parrot", "tiger", "dog", "fish"], a: 0, s: "A parrot can say hello.", e: "Con vẹt = parrot, loài chim biết nói." },
  { t: "t8", q: "Con mèo trong tiếng Anh là:", o: ["dog", "cat", "duck", "pig"], a: 1, s: "cat", e: "cat = con mèo. (dog = chó, duck = vịt, pig = lợn)" },
  { t: "t8", q: "Elephants are very ___. (to lớn)", o: ["small", "big", "thin", "short"], a: 1, s: "Elephants are very big.", e: "To lớn = big. (small = nhỏ, thin = gầy, short = thấp/ngắn)" },

  // ===== T9: Ngoại hình & quần áo =====
  { t: "t9", q: "\"What does she look like?\" — \"She is tall and ___.\"", o: ["slim", "Monday", "ten", "juice"], a: 0, s: "She is tall and slim.", e: "\"What does she look like?\" hỏi ngoại hình → trả lời bằng từ tả người: slim (mảnh mai)." },
  { t: "t9", q: "\"T-shirt\" có nghĩa là:", o: ["quần dài", "áo phông", "váy", "mũ"], a: 1, s: "T-shirt", e: "T-shirt = áo phông (áo hình chữ T)." },
  { t: "t9", q: "My brother is ___ than me. (cao hơn)", o: ["tall", "taller", "tallest", "more tall"], a: 1, s: "My brother is taller than me.", e: "So sánh hơn với từ ngắn: thêm -er + than → taller than (cao hơn)." },
  { t: "t9", q: "She is wearing a red ___. (váy)", o: ["dress", "shoes", "cap", "gloves"], a: 0, s: "She is wearing a red dress.", e: "Váy = dress. (shoes = giày, cap = mũ lưỡi trai, gloves = găng tay)" },
  { t: "t9", q: "\"How much is this shirt?\" — \"It's 50,000 ___.\"", o: ["dong", "o'clock", "years old", "kilos"], a: 0, s: "How much is this shirt?", e: "\"How much...?\" hỏi giá tiền → trả lời bằng tiền: 50,000 dong (đồng)." },
  { t: "t9", q: "\"shoes\" có nghĩa là:", o: ["tất", "giày", "dép", "mũ"], a: 1, s: "shoes", e: "shoes = giày. (socks = tất, sandals = dép, hat = mũ)" },
  { t: "t9", q: "My grandfather is old, but my brother is ___.", o: ["young", "tall", "big", "long"], a: 0, s: "My grandfather is old, but my brother is young.", e: "\"but\" chỉ sự trái ngược: old (già) >< young (trẻ)." },
  { t: "t9", q: "He has short black ___.", o: ["hair", "chair", "ruler", "water"], a: 0, s: "He has short black hair.", e: "hair = tóc: tóc đen ngắn (short black hair)." },
  { t: "t9", q: "\"jacket\" có nghĩa là:", o: ["áo khoác", "quần soóc", "khăn quàng", "áo dài"], a: 0, s: "jacket", e: "jacket = áo khoác. (shorts = quần soóc, scarf = khăn quàng)" },
  { t: "t9", q: "It's cold today. Put on your ___!", o: ["sandals", "jumper", "shorts", "sun hat"], a: 1, s: "It's cold today. Put on your jumper.", e: "Trời lạnh (cold) thì mặc áo len (jumper). Sandals, shorts, sun hat dùng khi trời nóng." },
  { t: "t9", q: "An elephant is ___ than a dog.", o: ["big", "bigger", "biggest", "more big"], a: 1, s: "An elephant is bigger than a dog.", e: "So sánh hơn: big → bigger than (to hơn). Gấp đôi chữ g rồi thêm -er." },
  { t: "t9", q: "\"trousers\" có nghĩa là:", o: ["quần dài", "áo sơ mi", "váy ngắn", "tất chân"], a: 0, s: "trousers", e: "trousers = quần dài. (shirt = áo sơ mi, skirt = váy ngắn, socks = tất)" },
  { t: "t9", q: "\"Whose skirt is this?\" — \"It's ___.\"", o: ["Mai's", "Mai", "on Mai", "at Mai"], a: 0, s: "Whose skirt is this? It's Mai's.", e: "\"Whose...?\" hỏi của ai → trả lời tên + 's chỉ sở hữu: It's Mai's (của Mai)." },
  { t: "t9", q: "My hair is long, but her hair is ___.", o: ["tall", "short", "old", "slow"], a: 1, s: "My hair is long, but her hair is short.", e: "\"but\" chỉ trái ngược: long (dài) >< short (ngắn)." },
  { t: "t9", q: "I wear a ___ on my head when it's sunny.", o: ["shoe", "hat", "sock", "glove"], a: 1, s: "I wear a hat on my head when it's sunny.", e: "Đội trên đầu (on my head) khi trời nắng là cái mũ (hat)." },

  // ===== T10: Nơi chốn & lễ hội =====
  { t: "t10", q: "\"Where were you yesterday?\" — \"I ___ at home.\"", o: ["am", "is", "was", "were"], a: 2, s: "Where were you yesterday? I was at home.", e: "\"yesterday\" (hôm qua) là quá khứ; chủ ngữ \"I\" → dùng \"was\"." },
  { t: "t10", q: "\"beach\" có nghĩa là:", o: ["ngọn núi", "bãi biển", "cánh đồng", "khu vườn"], a: 1, s: "beach", e: "beach = bãi biển. (mountain = núi, field = cánh đồng, garden = vườn)" },
  { t: "t10", q: "Tet is in ___ or February.", o: ["January", "June", "August", "October"], a: 0, s: "Tet is in January or February.", e: "Tết vào tháng 1 (January) hoặc tháng 2 (February)." },
  { t: "t10", q: "At Tet, children get lucky ___.", o: ["money", "water", "books", "chairs"], a: 0, s: "At Tet, children get lucky money.", e: "lucky money = tiền lì xì — trẻ em nhận vào dịp Tết." },
  { t: "t10", q: "\"Children's Day\" là ngày gì?", o: ["Ngày Nhà giáo", "Tết Trung thu", "Ngày Quốc tế Thiếu nhi", "Ngày Quốc khánh"], a: 2, s: "Children's Day", e: "Children's Day = Ngày Quốc tế Thiếu nhi 1/6 (children = trẻ em)." },
  { t: "t10", q: "Last summer, we ___ to Nha Trang.", o: ["go", "goes", "went", "going"], a: 2, s: "Last summer, we went to Nha Trang.", e: "\"Last summer\" (hè năm ngoái) là quá khứ → dùng \"went\" (quá khứ của go)." },
  { t: "t10", q: "\"zoo\" có nghĩa là:", o: ["công viên", "sở thú", "siêu thị", "rạp phim"], a: 1, s: "zoo", e: "zoo = sở thú. (park = công viên, supermarket = siêu thị, cinema = rạp phim)" },
  { t: "t10", q: "Ha Noi is the ___ of Vietnam.", o: ["beach", "capital", "mountain", "river"], a: 1, s: "Ha Noi is the capital of Vietnam.", e: "capital = thủ đô. Hà Nội là thủ đô của Việt Nam." },
  { t: "t10", q: "At Mid-Autumn Festival, children carry ___ and eat mooncakes.", o: ["lanterns", "schoolbags", "umbrellas", "bicycles"], a: 0, s: "Children carry lanterns and eat mooncakes.", e: "Trung thu trẻ em rước đèn lồng (lanterns) và ăn bánh trung thu (mooncakes)." },
  { t: "t10", q: "\"They were on the beach\" nghĩa là:", o: ["Họ đã ở trên núi.", "Họ đã ở bãi biển.", "Họ đang ở nhà.", "Họ sẽ đi bơi."], a: 1, s: "They were on the beach.", e: "were = đã ở (quá khứ), beach = bãi biển → Họ đã ở bãi biển." },
  { t: "t10", q: "\"Where is the bookshop?\" — \"It's ___ the cinema.\" (bên cạnh)", o: ["next to", "on", "under", "in"], a: 0, s: "The bookshop is next to the cinema.", e: "next to = bên cạnh. (on = trên, under = dưới, in = trong)" },
  { t: "t10", q: "\"supermarket\" có nghĩa là:", o: ["hiệu sách", "bệnh viện", "siêu thị", "bưu điện"], a: 2, s: "supermarket", e: "supermarket = siêu thị. (bookshop = hiệu sách, hospital = bệnh viện, post office = bưu điện)" },
  { t: "t10", q: "We watch ___ at Tet. (pháo hoa)", o: ["fireworks", "homework", "housework", "network"], a: 0, s: "We watch fireworks at Tet.", e: "Pháo hoa = fireworks (fire = lửa + works)." },
  { t: "t10", q: "\"mountain\" có nghĩa là:", o: ["dòng sông", "ngọn núi", "hòn đảo", "cái hồ"], a: 1, s: "mountain", e: "mountain = ngọn núi. (river = sông, island = đảo, lake = hồ)" },
  { t: "t10", q: "Yesterday, Mai and Nam ___ at the school festival.", o: ["was", "is", "were", "am"], a: 2, s: "Yesterday, Mai and Nam were at the school festival.", e: "\"Yesterday\" là quá khứ; \"Mai and Nam\" là số nhiều → dùng \"were\"." },
];

// ===== Dạng NHÌN HÌNH VIẾT TỪ =====
// img = hình emoji, w = đáp án hiển thị, accept = các đáp án được chấp nhận
const SPELL_BANK = [
  { t: "t8", img: "🐘", w: "elephant" },
  { t: "t8", img: "🐒", w: "monkey" },
  { t: "t8", img: "🦁", w: "lion" },
  { t: "t8", img: "🐯", w: "tiger" },
  { t: "t8", img: "🐻", w: "bear" },
  { t: "t8", img: "🐍", w: "snake" },
  { t: "t8", img: "🐴", w: "horse" },
  { t: "t8", img: "🐱", w: "cat" },
  { t: "t8", img: "🐶", w: "dog" },
  { t: "t8", img: "🦆", w: "duck" },
  { t: "t8", img: "🐟", w: "fish" },
  { t: "t7", img: "🍎", w: "apple" },
  { t: "t7", img: "🍌", w: "banana" },
  { t: "t7", img: "🥛", w: "milk" },
  { t: "t7", img: "🍞", w: "bread" },
  { t: "t7", img: "🍚", w: "rice" },
  { t: "t7", img: "🍗", w: "chicken" },
  { t: "t7", img: "🍊", w: "orange" },
  { t: "t7", img: "🥚", w: "egg" },
  { t: "t7", img: "🍦", w: "ice cream", accept: ["ice cream", "icecream", "ice-cream"] },
  { t: "t9", img: "👕", w: "T-shirt", accept: ["t-shirt", "tshirt", "t shirt", "shirt"] },
  { t: "t9", img: "👗", w: "dress" },
  { t: "t9", img: "👟", w: "shoes", accept: ["shoes", "shoe"] },
  { t: "t9", img: "🎩", w: "hat" },
  { t: "t9", img: "🧦", w: "socks", accept: ["socks", "sock"] },
  { t: "t9", img: "🧥", w: "jacket" },
  { t: "t3", img: "📖", w: "book" },
  { t: "t3", img: "✏️", w: "pencil" },
  { t: "t3", img: "🖊️", w: "pen" },
  { t: "t3", img: "📏", w: "ruler" },
  { t: "t3", img: "🎒", w: "school bag", accept: ["school bag", "schoolbag", "bag"] },
  { t: "t10", img: "🏖️", w: "beach" },
  { t: "t10", img: "⛰️", w: "mountain" },
];

// ===== Dạng SẮP XẾP TỪ THÀNH CÂU (viết lại câu) =====
const REORDER_BANK = [
  { t: "t1", sentence: "My name is Nam." },
  { t: "t1", sentence: "I am from Vietnam." },
  { t: "t1", sentence: "Nice to meet you." },
  { t: "t1", sentence: "How old are you?" },
  { t: "t2", sentence: "What time is it?" },
  { t: "t2", sentence: "Today is Monday." },
  { t: "t2", sentence: "My birthday is in May." },
  { t: "t3", sentence: "I have Maths on Mondays." },
  { t: "t3", sentence: "May I come in?" },
  { t: "t3", sentence: "I like Music and English." },
  { t: "t4", sentence: "I get up at six o'clock." },
  { t: "t4", sentence: "She does her homework every day." },
  { t: "t5", sentence: "I can ride a bike." },
  { t: "t5", sentence: "Can you play the piano?" },
  { t: "t6", sentence: "My father is a doctor." },
  { t: "t6", sentence: "There are four people in my family." },
  { t: "t7", sentence: "I would like some milk." },
  { t: "t7", sentence: "What is your favourite food?" },
  { t: "t8", sentence: "Monkeys like eating bananas." },
  { t: "t8", sentence: "Let's go to the zoo." },
  { t: "t9", sentence: "She is wearing a red dress." },
  { t: "t9", sentence: "My brother is taller than me." },
  { t: "t10", sentence: "We watch fireworks at Tet." },
  { t: "t10", sentence: "They were on the beach yesterday." },
];

// ===== Dạng NỐI HÌNH VỚI TỪ =====
const MATCH_BANK = [
  { t: "t8", pairs: [{ img: "🐘", w: "elephant" }, { img: "🦁", w: "lion" }, { img: "🐒", w: "monkey" }, { img: "🐍", w: "snake" }] },
  { t: "t8", pairs: [{ img: "🐱", w: "cat" }, { img: "🐶", w: "dog" }, { img: "🦆", w: "duck" }, { img: "🐴", w: "horse" }] },
  { t: "t8", pairs: [{ img: "🐯", w: "tiger" }, { img: "🐻", w: "bear" }, { img: "🐟", w: "fish" }, { img: "🐦", w: "bird" }] },
  { t: "t7", pairs: [{ img: "🍎", w: "apple" }, { img: "🥛", w: "milk" }, { img: "🍞", w: "bread" }, { img: "🍚", w: "rice" }] },
  { t: "t7", pairs: [{ img: "🍌", w: "banana" }, { img: "🍊", w: "orange" }, { img: "🍇", w: "grapes" }, { img: "🥚", w: "egg" }] },
  { t: "t9", pairs: [{ img: "👕", w: "T-shirt" }, { img: "👗", w: "dress" }, { img: "👟", w: "shoes" }, { img: "🧦", w: "socks" }] },
  { t: "t9", pairs: [{ img: "🎩", w: "hat" }, { img: "🧤", w: "gloves" }, { img: "🧥", w: "jacket" }, { img: "👖", w: "trousers" }] },
  { t: "t3", pairs: [{ img: "📖", w: "book" }, { img: "✏️", w: "pencil" }, { img: "📏", w: "ruler" }, { img: "🎒", w: "school bag" }] },
  { t: "t5", pairs: [{ img: "🏊", w: "swim" }, { img: "🎤", w: "sing" }, { img: "💃", w: "dance" }, { img: "🏃", w: "run" }] },
  { t: "t10", pairs: [{ img: "🎆", w: "fireworks" }, { img: "🏮", w: "lantern" }, { img: "🏖️", w: "beach" }, { img: "⛰️", w: "mountain" }] },
];

// Gán cấp độ mặc định: 1 = Cơ bản cho các câu/dạng đã có
QUESTION_BANK.forEach(q => { if (q.d === undefined) q.d = 1; });
SPELL_BANK.forEach(q => { if (q.d === undefined) q.d = 1; });
REORDER_BANK.forEach(q => { if (q.d === undefined) q.d = 1; });
MATCH_BANK.forEach(q => { if (q.d === undefined) q.d = 1; });

// ===== NGÂN HÀNG NÂNG CAO (d:2) — phục vụ ôn thi & học sinh giỏi =====

// --- Trắc nghiệm ngữ pháp/từ vựng nâng cao ---
const ADVANCED_BANK = [
  { t: "t9", d: 2, q: "This box is ___ than that one. (heavy)", o: ["heavy", "heavier", "heaviest", "more heavy"], a: 1, s: "This box is heavier than that one.", e: "So sánh hơn với tính từ ngắn tận cùng '-y': heavy → heavier + than." },
  { t: "t10", d: 2, q: "Mount Everest is the ___ mountain in the world.", o: ["high", "higher", "highest", "more high"], a: 2, s: "Mount Everest is the highest mountain.", e: "So sánh nhất tính từ ngắn: the + tính từ + '-est' → the highest." },
  { t: "t7", d: 2, q: "How ___ apples do you have?", o: ["much", "many", "old", "long"], a: 1, s: "How many apples do you have?", e: "'apples' đếm được, số nhiều → dùng 'many'." },
  { t: "t7", d: 2, q: "How ___ water is there?", o: ["many", "much", "old", "far"], a: 1, s: "How much water is there?", e: "'water' không đếm được → dùng 'much'." },
  { t: "t4", d: 2, q: "Look! The children ___ in the garden now.", o: ["play", "plays", "are playing", "played"], a: 2, s: "The children are playing in the garden now.", e: "'Look!' và 'now' → thì hiện tại tiếp diễn: are + V-ing." },
  { t: "t10", d: 2, q: "Last summer we ___ to Da Nang.", o: ["go", "goes", "went", "going"], a: 2, s: "Last summer we went to Da Nang.", e: "'Last summer' là quá khứ → 'went' (quá khứ của go)." },
  { t: "t4", d: 2, q: "She usually ___ TV in the evening.", o: ["watch", "watches", "watching", "watched"], a: 1, s: "She usually watches TV in the evening.", e: "'usually' → hiện tại đơn; 'She' ngôi 3 số ít, tận cùng -ch → watches." },
  { t: "t3", d: 2, q: "___ is your favourite subject? — Maths.", o: ["Who", "What", "Where", "When"], a: 1, s: "What is your favourite subject?", e: "Hỏi 'cái gì' → What." },
  { t: "t2", d: 2, q: "___ do you go to school? — At seven o'clock.", o: ["What time", "Where", "Who", "Why"], a: 0, s: "What time do you go to school?", e: "Trả lời bằng giờ → câu hỏi 'What time'." },
  { t: "t8", d: 2, q: "___ do you like tigers? — Because they are strong.", o: ["What", "Where", "Why", "When"], a: 2, s: "Why do you like tigers?", e: "Trả lời 'Because...' → câu hỏi 'Why' (tại sao)." },
  { t: "t6", d: 2, q: "These are my books. ___ are on the table.", o: ["It", "They", "He", "She"], a: 1, s: "They are on the table.", e: "'books' số nhiều, chỉ vật → thay bằng 'They'." },
  { t: "t9", d: 2, q: "That is Nam. ___ bag is blue.", o: ["He", "His", "Him", "She"], a: 1, s: "His bag is blue.", e: "Tính từ sở hữu của 'he' là 'His' (của cậu ấy)." },
  { t: "t1", d: 2, q: "I have a sister. ___ name is Hoa.", o: ["He", "His", "Her", "She"], a: 2, s: "Her name is Hoa.", e: "Tính từ sở hữu của 'she' là 'Her' (của cô ấy)." },
  { t: "t3", d: 2, q: "There ___ some books on the desk.", o: ["is", "are", "am", "be"], a: 1, s: "There are some books on the desk.", e: "'some books' số nhiều → 'There are'." },
  { t: "t7", d: 2, q: "There ___ some milk in the glass.", o: ["is", "are", "am", "be"], a: 0, s: "There is some milk in the glass.", e: "'milk' không đếm được → 'There is'." },
  { t: "t5", d: 2, q: "My brother is good ___ playing football.", o: ["at", "in", "on", "for"], a: 0, s: "My brother is good at playing football.", e: "Cụm cố định 'good at' = giỏi về việc gì." },
  { t: "t10", d: 2, q: "The cat is ___ the table. (bên trên)", o: ["on", "in", "at", "of"], a: 0, s: "The cat is on the table.", e: "'on' = ở trên bề mặt." },
  { t: "t4", d: 2, q: "I go to school ___ bike.", o: ["by", "on", "in", "with"], a: 0, s: "I go to school by bike.", e: "Đi bằng phương tiện dùng 'by': by bike, by bus." },
  { t: "t2", d: 2, q: "My birthday is ___ the 5th of May.", o: ["in", "on", "at", "to"], a: 1, s: "My birthday is on the 5th of May.", e: "Trước một ngày cụ thể dùng 'on'." },
  { t: "t9", d: 2, q: "Nga sings ___ than Lan.", o: ["good", "well", "better", "best"], a: 2, s: "Nga sings better than Lan.", e: "So sánh hơn của trạng từ 'well' là 'better'." },
  { t: "t4", d: 2, q: "They don't ___ any homework today.", o: ["has", "have", "having", "to have"], a: 1, s: "They don't have any homework today.", e: "Sau 'don't' dùng động từ nguyên thể → 'have'." },
  { t: "t8", d: 2, q: "An elephant is bigger ___ a dog.", o: ["then", "than", "that", "as"], a: 1, s: "An elephant is bigger than a dog.", e: "So sánh hơn luôn đi với 'than' (không phải 'then')." },
  { t: "t1", d: 2, q: "___ you speak English? — Yes, I can.", o: ["Do", "Are", "Can", "Is"], a: 2, s: "Can you speak English?", e: "Trả lời 'Yes, I can' → câu hỏi bắt đầu bằng 'Can'." },
  { t: "t6", d: 2, q: "My mother works ___ a hospital.", o: ["in", "on", "at", "by"], a: 0, s: "My mother works in a hospital.", e: "'work in a hospital/school/factory' = làm việc ở đâu." },
];

// --- Chọn từ KHÁC LOẠI (odd one out) ---
const ODD_BANK = [
  { t: "t8", words: ["dog", "cat", "apple", "fish"], odd: 2, e: "'apple' là trái cây, còn lại đều là con vật." },
  { t: "t7", words: ["milk", "water", "juice", "bread"], odd: 3, e: "'bread' là đồ ăn, còn lại là đồ uống." },
  { t: "t3", words: ["Maths", "English", "Music", "pencil"], odd: 3, e: "'pencil' là đồ dùng, còn lại là môn học." },
  { t: "t2", words: ["Monday", "Friday", "May", "Sunday"], odd: 2, e: "'May' là tháng, còn lại là thứ trong tuần." },
  { t: "t9", words: ["shoes", "dress", "hat", "table"], odd: 3, e: "'table' là đồ vật, còn lại là quần áo/đồ đội đầu." },
  { t: "t6", words: ["doctor", "nurse", "teacher", "hospital"], odd: 3, e: "'hospital' là nơi chốn, còn lại là nghề nghiệp." },
  { t: "t1", words: ["Japan", "England", "Vietnamese", "America"], odd: 2, e: "'Vietnamese' là quốc tịch, còn lại là tên nước." },
  { t: "t7", words: ["apple", "banana", "orange", "chicken"], odd: 3, e: "'chicken' là thịt, còn lại là trái cây." },
  { t: "t5", words: ["swim", "sing", "dance", "book"], odd: 3, e: "'book' là danh từ, còn lại là động từ chỉ hành động." },
  { t: "t8", words: ["lion", "tiger", "bear", "rose"], odd: 3, e: "'rose' là hoa, còn lại là con vật." },
  { t: "t2", words: ["January", "March", "June", "Wednesday"], odd: 3, e: "'Wednesday' là thứ, còn lại là tháng." },
  { t: "t4", words: ["read", "write", "play", "happy"], odd: 3, e: "'happy' là tính từ, còn lại là động từ." },
  { t: "t10", words: ["beach", "mountain", "river", "milk"], odd: 3, e: "'milk' là đồ uống, còn lại là nơi chốn thiên nhiên." },
  { t: "t3", words: ["pen", "ruler", "rubber", "run"], odd: 3, e: "'run' là động từ, còn lại là đồ dùng học tập." },
  { t: "t9", words: ["tall", "short", "slim", "jump"], odd: 3, e: "'jump' là động từ, còn lại là tính từ tả người." },
  { t: "t6", words: ["mother", "father", "sister", "teacher"], odd: 3, e: "'teacher' là nghề nghiệp, còn lại là thành viên gia đình." },
  { t: "t7", words: ["hungry", "thirsty", "tired", "bread"], odd: 3, e: "'bread' là đồ ăn, còn lại là tính từ chỉ cảm giác." },
  { t: "t5", words: ["can", "swim", "run", "jump"], odd: 0, e: "'can' là động từ khuyết thiếu, còn lại là động từ chỉ hành động." },
  { t: "t8", words: ["big", "small", "tall", "zoo"], odd: 3, e: "'zoo' là nơi chốn, còn lại là tính từ." },
  { t: "t2", words: ["morning", "afternoon", "evening", "yellow"], odd: 3, e: "'yellow' là màu sắc, còn lại là buổi trong ngày." },
];

// --- Tìm phần SAI trong câu (error identification) ---
// parts: 4 phần của câu; a: chỉ số phần sai
const ERROR_BANK = [
  { t: "t1", parts: ["She", "are", "my", "friend."], a: 1, e: "'She' (số ít) phải đi với 'is'. Câu đúng: She is my friend." },
  { t: "t4", parts: ["He", "get up", "at", "6 o'clock."], a: 1, e: "'He' ngôi 3 số ít → 'gets up'. Câu đúng: He gets up at 6 o'clock." },
  { t: "t5", parts: ["I", "can", "to swim", "well."], a: 2, e: "Sau 'can' dùng động từ nguyên thể, bỏ 'to'. Câu đúng: I can swim well." },
  { t: "t2", parts: ["My birthday", "is", "on", "May."], a: 2, e: "Trước tháng dùng 'in'. Câu đúng: My birthday is in May." },
  { t: "t6", parts: ["There", "is", "four", "people."], a: 1, e: "'four people' số nhiều → 'are'. Câu đúng: There are four people." },
  { t: "t7", parts: ["I", "would like", "some", "waters."], a: 3, e: "'water' không đếm được, không thêm 's'. Câu đúng: ... some water." },
  { t: "t3", parts: ["We", "has", "English", "today."], a: 1, e: "'We' → 'have'. Câu đúng: We have English today." },
  { t: "t8", parts: ["A bird", "can", "flies", "high."], a: 2, e: "Sau 'can' dùng nguyên thể 'fly'. Câu đúng: A bird can fly high." },
  { t: "t9", parts: ["She", "is", "tall", "than me."], a: 2, e: "So sánh hơn → 'taller than'. Câu đúng: She is taller than me." },
  { t: "t4", parts: ["They", "plays", "football", "every day."], a: 1, e: "'They' số nhiều → 'play'. Câu đúng: They play football every day." },
  { t: "t7", parts: ["Do", "you", "likes", "fish?"], a: 2, e: "Sau 'Do you' dùng nguyên thể 'like'. Câu đúng: Do you like fish?" },
  { t: "t10", parts: ["Yesterday", "I", "am", "at home."], a: 2, e: "'Yesterday' là quá khứ → 'was'. Câu đúng: Yesterday I was at home." },
  { t: "t6", parts: ["My father", "is", "a", "teachers."], a: 3, e: "Số ít 'a teacher', không thêm 's'. Câu đúng: My father is a teacher." },
  { t: "t3", parts: ["I", "have", "Maths", "in Monday."], a: 3, e: "Trước thứ dùng 'on': on Monday. Câu đúng: I have Maths on Monday." },
  { t: "t5", parts: ["Can", "your sister", "cooks", "dinner?"], a: 2, e: "Sau 'Can + chủ ngữ' dùng nguyên thể 'cook'. Câu đúng: Can your sister cook dinner?" },
  { t: "t8", parts: ["I", "don't", "likes", "snakes."], a: 2, e: "Sau 'don't' dùng nguyên thể 'like'. Câu đúng: I don't like snakes." },
];

// --- Viết lại câu (sentence transformation) ---
// original: câu gốc; given: gợi ý bắt đầu (có thể trống); answer: đáp án; accept: các cách chấp nhận
const TRANSFORM_BANK = [
  { t: "t5", original: "She can swim.", prompt: "Viết lại ở dạng PHỦ ĐỊNH:", answer: "She can't swim.", accept: ["she can't swim", "she cannot swim", "she can not swim"], e: "Phủ định của 'can' là 'can't' (cannot)." },
  { t: "t7", original: "I like apples.", prompt: "Viết lại ở dạng PHỦ ĐỊNH:", answer: "I don't like apples.", accept: ["i don't like apples", "i do not like apples"], e: "Phủ định hiện tại đơn với 'I' dùng 'don't + động từ'." },
  { t: "t4", original: "He plays football.", prompt: "Viết lại ở dạng PHỦ ĐỊNH:", answer: "He doesn't play football.", accept: ["he doesn't play football", "he does not play football"], e: "Ngôi 3 số ít phủ định dùng 'doesn't + động từ nguyên thể'." },
  { t: "t1", original: "You are from Vietnam.", prompt: "Viết lại thành CÂU HỎI:", answer: "Are you from Vietnam?", accept: ["are you from vietnam"], e: "Đưa 'are' lên đầu câu để tạo câu hỏi." },
  { t: "t5", original: "She can dance.", prompt: "Viết lại thành CÂU HỎI:", answer: "Can she dance?", accept: ["can she dance"], e: "Đưa 'can' lên đầu câu để tạo câu hỏi." },
  { t: "t8", original: "An elephant is big. A mouse is small.", prompt: "Nối thành câu SO SÁNH:", given: "An elephant is ___ a mouse.", answer: "An elephant is bigger than a mouse.", accept: ["an elephant is bigger than a mouse"], e: "big → bigger than (to hơn)." },
  { t: "t6", original: "Nam is 10 years old. Mai is 8 years old.", prompt: "Viết câu SO SÁNH dùng 'older':", answer: "Nam is older than Mai.", accept: ["nam is older than mai"], e: "Nhiều tuổi hơn = older than." },
  { t: "t8", original: "This is a book.", prompt: "Chuyển sang SỐ NHIỀU:", answer: "These are books.", accept: ["these are books"], e: "this → these, is → are, book → books." },
  { t: "t8", original: "It is a cat.", prompt: "Chuyển sang SỐ NHIỀU:", answer: "They are cats.", accept: ["they are cats"], e: "it → they, is → are, cat → cats." },
  { t: "t9", original: "This book belongs to Mai.", prompt: "Viết lại dùng sở hữu ('s):", given: "This is ___ book.", answer: "This is Mai's book.", accept: ["this is mai's book"], e: "Sở hữu dùng 's: Mai's book (sách của Mai)." },
  { t: "t4", original: "I go to school every day.", prompt: "Viết lại ở dạng PHỦ ĐỊNH:", answer: "I don't go to school every day.", accept: ["i don't go to school every day", "i do not go to school every day"], e: "Phủ định với 'I' dùng 'don't + động từ'." },
  { t: "t3", original: "They are students.", prompt: "Viết lại thành CÂU HỎI:", answer: "Are they students?", accept: ["are they students"], e: "Đưa 'are' lên đầu câu." },
  { t: "t5", original: "He can play the piano.", prompt: "Viết lại ở dạng PHỦ ĐỊNH:", answer: "He can't play the piano.", accept: ["he can't play the piano", "he cannot play the piano"], e: "Phủ định của 'can' là 'can't'." },
  { t: "t9", original: "Lan is shorter than Hoa.", prompt: "Viết lại dùng 'taller':", given: "Hoa is ___ than Lan.", answer: "Hoa is taller than Lan.", accept: ["hoa is taller than lan"], e: "Đảo chủ ngữ thì 'shorter' (thấp hơn) đổi thành 'taller' (cao hơn)." },
];

// --- Đọc hiểu (reading comprehension) — mỗi đoạn có nhiều câu hỏi ---
const READING_BANK = [
  {
    t: "t6",
    passage: "Hello. My name is Mai. I am nine years old. I am from Ha Noi. There are four people in my family: my father, my mother, my brother and me. My father is a doctor. My mother is a teacher.",
    questions: [
      { q: "How old is Mai?", o: ["eight", "nine", "ten", "seven"], a: 1, e: "Bài đọc: 'I am nine years old.'" },
      { q: "Where is Mai from?", o: ["Ha Noi", "Hue", "Da Nang", "Sai Gon"], a: 0, e: "Bài đọc: 'I am from Ha Noi.'" },
      { q: "What does Mai's father do?", o: ["teacher", "doctor", "farmer", "driver"], a: 1, e: "Bài đọc: 'My father is a doctor.'" },
      { q: "How many people are in Mai's family?", o: ["three", "four", "five", "six"], a: 1, e: "Bài đọc: 'There are four people in my family.'" },
    ],
  },
  {
    t: "t4",
    passage: "Tom is a pupil. Every morning, he gets up at six o'clock. He has breakfast at half past six. He goes to school at seven. In the afternoon, he plays football with his friends. In the evening, he does his homework and goes to bed at nine.",
    questions: [
      { q: "What time does Tom get up?", o: ["6:00", "6:30", "7:00", "9:00"], a: 0, e: "Bài đọc: 'he gets up at six o'clock.'" },
      { q: "What does Tom do in the afternoon?", o: ["does homework", "plays football", "sleeps", "has breakfast"], a: 1, e: "Bài đọc: 'he plays football with his friends.'" },
      { q: "When does Tom go to bed?", o: ["seven", "eight", "nine", "ten"], a: 2, e: "Bài đọc: 'goes to bed at nine.'" },
    ],
  },
  {
    t: "t8",
    passage: "Last Sunday, Nam went to the zoo with his family. He saw many animals. He saw big elephants, tall giraffes and funny monkeys. The monkeys were eating bananas. Nam liked the monkeys best because they were very funny.",
    questions: [
      { q: "Where did Nam go last Sunday?", o: ["the zoo", "the beach", "school", "the park"], a: 0, e: "Bài đọc: 'Nam went to the zoo.'" },
      { q: "What were the monkeys eating?", o: ["apples", "bananas", "bread", "rice"], a: 1, e: "Bài đọc: 'The monkeys were eating bananas.'" },
      { q: "Which animal did Nam like best?", o: ["elephants", "giraffes", "monkeys", "lions"], a: 2, e: "Bài đọc: 'Nam liked the monkeys best.'" },
    ],
  },
  {
    t: "t10",
    passage: "Tet is the biggest festival in Vietnam. It is in January or February. At Tet, families clean and decorate their houses. Children wear new clothes and get lucky money. People eat banh chung and watch fireworks.",
    questions: [
      { q: "When is Tet?", o: ["January or February", "May", "September", "December"], a: 0, e: "Bài đọc: 'It is in January or February.'" },
      { q: "What do children get at Tet?", o: ["books", "lucky money", "toys", "pens"], a: 1, e: "Bài đọc: 'Children ... get lucky money.'" },
      { q: "What do people watch at Tet?", o: ["films", "fireworks", "football", "TV"], a: 1, e: "Bài đọc: 'watch fireworks.'" },
    ],
  },
];
